yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>', views.group_posts, name='group_list')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls), ]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Заголовок'
    )
    slug = models.SlugField(
        max_length=200,
        unique=True,
        verbose_name='Слаг',
    )
    description = models.TextField(
        max_length=400,
        verbose_name='Описание'
    )

    class Meta:
        verbose_name_plural = 'Группы'
        verbose_name = 'Группа'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'

yatube/posts/views.py
from .models import Post, Group
from django.shortcuts import get_object_or_404, render

COUNT_POST: int = 10


def index(request):
    posts = Post.objects.all().order_by('-pub_date')[:COUNT_POST]
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all().order_by('-pub_date')[:COUNT_POST]
    context = {
        'group': group,
        'posts': posts,
    }
    template = 'posts/group_list.html'
    return render(request, template, context)

yatube/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="css/bootstrap.min.css">
  <title>
      {% block title %}{% endblock %}
  </title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
        <article>
            {% block content %}
                Контент не подвезли :(
            {% endblock %}
        </article>
    </main>
    <footer>
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="page-footer font-small blue border-top">
  <div class="footer-copyright text-center py-3">© 2022 Copyright
    <p><span style="color:red">Ya</span>tube</p>
  </div>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'post:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
    </div>
  </nav>
</header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества: {{ group.title }}{% endblock %}
{% include 'includes/header.html' %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
      {{ group.description|linebreaks }}
    </p>
    {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        <a href="{% url 'post:group_list' post.group.slug %}">все записи группы</a>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
{% endblock %}
{% include 'includes/footer.html' %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% include 'includes/header.html' %}
{% block content %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
      {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
            {% if post.group %}
                <a href="{% url 'post:group_list' post.group.slug %}" class="btn btn-primary">Все записи группы"{{ post.group }}"</a>
            {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
  </div>
{% endblock %}
{% include 'includes/footer.html' %}